Repository jhunterh/Cache-Hierarchy-Simulation-Tool, pull requests merged in 2024-04, with the labels that each got.

#31 24 need to formalize dataset structure and create a dataset parser for the simulator
  DataGenerator/include/DatafileController.h
  DataGenerator/makefile.rules
  DataGenerator/src/DataGenerator.cpp
  DataGenerator/src/DatafileController.cpp
  DataGenerator/test/Makefile
  DataGenerator/test/src/DatafileControllerTest.cpp
  Makefile
  README.md
  runDataGeneratorTool.bash
  simulator-example/src/simulation.cpp
  simulator/Makefile
  simulator/include/DatasetParser.h
  simulator/include/api.h
  simulator/include/basiccache.h
  simulator/include/cache.h
  simulator/include/cacheinterface.h
  simulator/include/core.h
  simulator/include/replacementpolicy/firstinfirstout.h
  simulator/include/replacementpolicy/lastinfirstout.h
  simulator/include/replacementpolicy/policyinterface.h
  simulator/include/system.h
  simulator/include/types.h
  simulator/src/DatasetParser.cpp
  simulator/src/basiccache.cpp
  simulator/src/core.cpp
  simulator/src/system.cpp
  zipDataset.bash
Labels: enhancement

#39 add threadid to trace file
  DataGenerator/src/DataGenerator.cpp
  DataGenerator/test/src/DatafileControllerTest.cpp
  simulator/include/api.h
Labels: enhancement, high priority

#40 27 add cache system configuration by json file
  DataGenerator/include/DatafileController.h
  DataGenerator/src/DataGenerator.cpp
  DataGenerator/test/src/DatafileControllerTest.cpp
  Makefile
  basic_config.json
  simulator-example/src/simulation.cpp
  simulator/CMakeLists.txt
  simulator/include/api.h
  simulator/include/basiccache.h
  simulator/include/cacheinterface.h
  simulator/include/configparser.h
  simulator/include/core.h
  simulator/include/datasetparser.h
  simulator/include/instruction.h
  simulator/include/nlohmann/json.hpp
  simulator/include/nlohmann/json_fwd.hpp
  simulator/include/replacementpolicy/firstinfirstout.h
  simulator/include/replacementpolicy/lastinfirstout.h
  simulator/include/replacementpolicy/policyinterface.h
  simulator/include/replacementpolicy/policylist.h
  simulator/include/system.h
  simulator/include/types.h
  simulator/src/api.cpp
  simulator/src/basiccache.cpp
  simulator/src/configparser.cpp
  simulator/src/core.cpp
  simulator/src/datasetparser.cpp
  simulator/src/replacementpolicy/firstinfirstout.cpp
  simulator/src/replacementpolicy/lastinfirstout.cpp
  simulator/src/system.cpp
Labels: enhancement, high priority

#44 Add unit tests for simulator (Part 1)
  .gitignore
  simulator/CMakeLists.txt
  simulator/Makefile
  simulator/include/basiccache.h
  simulator/include/cacheinterface.h
  simulator/include/replacementpolicy/firstinfirstout.h
  simulator/include/replacementpolicy/lastinfirstout.h
  simulator/include/replacementpolicy/policyinterface.h
  simulator/include/system.h
  simulator/src/basiccache.cpp
  simulator/src/core.cpp
  simulator/src/replacementpolicy/firstinfirstout.cpp
  simulator/src/replacementpolicy/lastinfirstout.cpp
  simulator/test/test.cpp
  simulator/test/test_basiccache.cpp
  third_party/doctest.h
Labels: enhancement, high priority

#49 45 update config file structure
  DataGenerator/include/DatafileController.h
  DataGenerator/makefile.rules
  DataGenerator/src/DatafileController.cpp
  DataGenerator/test/Makefile
  DataGenerator/test/include/doctest.h
  Makefile
  basic_config.json
  simulator-example/src/simulation.cpp
  simulator/CMakeLists.txt
  simulator/include/configparser.h
  simulator/include/system.h
  simulator/include/types.h
  simulator/src/basiccache.cpp
  simulator/src/configparser.cpp
  simulator/src/system.cpp
  simulator/test/test_api.cpp
  simulator/test/test_core.cpp
  simulator/test/test_firstinfirstout.cpp
  simulator/test/test_lastinfirstout.cpp
  simulator/test/test_system.cpp
  third_party/nlohmann/json.hpp
  third_party/nlohmann/json_fwd.hpp
Labels: enhancement, high priority

#51 46 look into running spec benchmarks
  DataGenerator/Benchmarks/Makefile
  DataGenerator/Benchmarks/forkTest
  DataGenerator/Benchmarks/parallelSimpleTest
  DataGenerator/Benchmarks/simpleTest
  DataGenerator/makefile.rules
  DataGenerator/src/DataGenerator.cpp
  DataGenerator/src/DatafileController.cpp
  DataGenerator/test/src/DatafileControllerTest.cpp
  runDataGeneratorTool.bash
  simulator-example/src/simulation.cpp
  simulator/include/api.h
  simulator/include/datasetparser.h
  simulator/include/instruction.h
  simulator/include/system.h
  simulator/src/api.cpp
  simulator/src/configparser.cpp
  simulator/src/datasetparser.cpp
  simulator/src/system.cpp
Labels: enhancement, high priority

#54 fix unit test build
  simulator/test/test_api.cpp
  simulator/test/test_system.cpp
Labels: bug, high priority

#58 56 add more benchmark programs
  DataGenerator/Benchmarks/Makefile
  DataGenerator/tests/Makefile
  DataGenerator/tests/forkTest.cpp
  DataGenerator/tests/matrixMultFork.cpp
  DataGenerator/tests/matrixMultForkIneff.cpp
  DataGenerator/tests/matrixMultOpenMP.cpp
  DataGenerator/tests/matrixMultOpenMPIneff.cpp
  DataGenerator/tests/matrixMultSingle.cpp
  DataGenerator/tests/matrixMultSingleIneff.cpp
  DataGenerator/tests/parallelSimpleTest.cpp
  DataGenerator/tests/simpleTest.cpp
  Makefile
  runDataGeneratorTool.bash
  simulator-main/src/simulation.cpp
  tool_env.bash
Labels: enhancement
